### ISSUE TITLE
GraphQL authentication

### ISSUE THREAD

**Issue by dannyshafer** [kiva/ui#1467]
Hi team!

Is there an example of how one would authenticate an Apollo client? From what I understood, the closest I saw was something like this: https://github.com/kiva/ui/blob/d6c5ccf689f156ddd345af99cb0a27a7c7080e83/src/main.js#L38

but it seems like that's dependent on the `kvis` token already being from the browser. https://github.com/kiva/ui/blob/34391d5e3e55be0c2fddd919a522b9a5a0658dd0/src/client-entry.js#L41

Is there an endpoint, for example, that one could pass a username and password to, which returns a token that can then be used to authenticate the Apollo client? Thanks!

**Comment by mcstover** [comment]
@dannyshafer Thank you for reaching out. At this time we don't grant external access to protected user information or actions through the GraphQL api. This is something that will be added in future and will allow a 3rd party or individual to get an access token to query or update some information.

**Comment by go-bears** [comment]
Hi @dannyshafer! thanks for your interest in working with Kiva data. It sounds like you're building an app for yourself. Going to invite you to join the Build-Kiva Google Group and post your question to the Build community to continue this conversation. 
https://groups.google.com/forum/#!forum/build-kiva

Will be closing the issue as developer questions are fielded in the google group rather than in the issues trackers. 

More information on working the GraphQL endpoint can be found here:
https://www.kiva.org/build

And if you're interested in general in participating in open source projects in General
Kiva's crowdvet project is currently open to open source volunteers:
https://github.com/kiva/crowdvet.org

Hope this helps!
